namespace AgentSmith.Tests.Architecture;

/// <summary>
/// p0402: locates the hand-written backend sources the architecture rules read.
/// Generated code (EF migrations, anything carrying an auto-generated header) is
/// not authored, so it is not judged.
/// </summary>
internal static class ArchitectureSources
{
    public static string BackendRoot { get; } = Resolve("src", "backend");

    public static string TestSourceRoot { get; } = Resolve("tests", "AgentSmith.Tests");

    public static IEnumerable<string> HandWrittenBackendFiles() =>
        Directory.EnumerateFiles(BackendRoot, "*.cs", SearchOption.AllDirectories)
            .Where(p => !p.Contains($"{Path.DirectorySeparatorChar}obj{Path.DirectorySeparatorChar}",
                            StringComparison.Ordinal)
                        && !p.Contains($"{Path.DirectorySeparatorChar}bin{Path.DirectorySeparatorChar}",
                            StringComparison.Ordinal)
                        && !p.Contains($"{Path.DirectorySeparatorChar}Migrations{Path.DirectorySeparatorChar}",
                            StringComparison.Ordinal))
            .Where(p => !IsGenerated(p));

    private static bool IsGenerated(string path)
    {
        using var reader = new StreamReader(path);
        var buffer = new char[400];
        var read = reader.Read(buffer, 0, buffer.Length);
        return new string(buffer, 0, read).Contains("<auto-generated", StringComparison.Ordinal);
    }

    private static string Resolve(params string[] segments)
    {
        var dir = AppContext.BaseDirectory;
        for (var i = 0; i < 10; i++)
        {
            var candidate = Path.Combine([dir, .. segments]);
            if (Directory.Exists(candidate)) return candidate;
            var parent = Directory.GetParent(dir);
            if (parent is null) break;
            dir = parent.FullName;
        }
        throw new InvalidOperationException(
            $"Could not locate {Path.Combine(segments)} from '{AppContext.BaseDirectory}'");
    }
}
