using System.Text.RegularExpressions;
using AgentSmith.Contracts.Models;
using AgentSmith.Contracts.Sandbox;
using AgentSmith.Infrastructure.Services.Security;
using FluentAssertions;

namespace AgentSmith.Tests.Services;

/// <summary>
/// p0333c: files that self-declare as generated (Roslyn &lt;auto-generated&gt; convention)
/// are regenerated from a template, so hand-review vuln patterns only produce noise there.
/// Those are skipped; secret patterns still run so a credential in generated output trips.
/// </summary>
public sealed class PatternFileMatcherTests
{
    private readonly PatternFileMatcher _matcher = new();

    [Fact]
    public async Task ScanFile_GeneratedFile_SkipsVulnPatterns()
    {
        var findings = await Scan(
            "// <auto-generated/>\nvar q = ExecuteSql(llmOutput);\n",
            VulnPattern("llm-output-in-sql", "ExecuteSql"));

        findings.Should().BeEmpty("a vuln pattern must not fire on self-declared generated code");
    }

    [Fact]
    public async Task ScanFile_GeneratedFile_StillRunsSecretPatterns()
    {
        var findings = await Scan(
            "// <auto-generated/>\nconst key = \"AKIAIOSFODNN7EXAMPLE\";\n",
            SecretPattern("aws-access-key", "AKIA[0-9A-Z]{16}"));

        findings.Should().ContainSingle("a hardcoded credential in generated output must still trip");
    }

    [Fact]
    public async Task ScanFile_HandWrittenFile_RunsVulnPatterns()
    {
        var findings = await Scan(
            "var q = ExecuteSql(llmOutput);\n",
            VulnPattern("llm-output-in-sql", "ExecuteSql"));

        findings.Should().ContainSingle("hand-written code keeps full pattern coverage");
    }

    private Task<List<PatternFinding>> Scan(string content, CompiledPattern pattern) =>
        _matcher.ScanFileAsync(
            new SingleFileReader(content), "/work/File.cs", "File.cs", [pattern], CancellationToken.None);

    private static CompiledPattern VulnPattern(string id, string regex) => Compile(id, "ai-security", regex);
    private static CompiledPattern SecretPattern(string id, string regex) => Compile(id, "secrets", regex);

    private static CompiledPattern Compile(string id, string category, string regex) =>
        new(new Regex(regex), new PatternDefinition(
            Id: id, Category: category, Regex: regex, Severity: "high", Confidence: 7,
            Title: id, Description: "test pattern", Cwe: null));

    private sealed class SingleFileReader(string content) : ISandboxFileReader
    {
        public Task<bool> ExistsAsync(string path, CancellationToken ct) => Task.FromResult(true);
        public Task<string?> TryReadAsync(string path, CancellationToken ct) => Task.FromResult<string?>(content);
        public Task<string> ReadRequiredAsync(string path, CancellationToken ct) => Task.FromResult(content);
        public Task WriteAsync(string path, string c, CancellationToken ct) => Task.CompletedTask;
        public Task<IReadOnlyList<string>> ListAsync(string path, int? maxDepth, CancellationToken ct)
            => Task.FromResult<IReadOnlyList<string>>([]);
    }
}
