using System.Text.RegularExpressions;
using AgentSmith.Contracts.Models;
using AgentSmith.Contracts.Sandbox;

namespace AgentSmith.Infrastructure.Services.Security;

/// <summary>
/// Matches compiled regex patterns against individual file contents fetched
/// through ISandboxFileReader so the scan reads the sandbox tree directly.
/// </summary>
public sealed class PatternFileMatcher
{
    public async Task<List<PatternFinding>> ScanFileAsync(
        ISandboxFileReader reader,
        string filePath,
        string relativePath,
        IReadOnlyList<CompiledPattern> patterns,
        CancellationToken cancellationToken)
    {
        var findings = new List<PatternFinding>();

        var content = await reader.TryReadAsync(filePath, cancellationToken);
        if (content is null) return findings;
        var lines = content.Split('\n');

        // p0333c: generated code declares itself (Roslyn <auto-generated> convention). It is
        // regenerated from a template, so hand-review vuln patterns only produce noise there
        // (a generated API client tripped the ai-security "LLM Output in SQL" rule). Skip those,
        // but keep secret patterns so a credential baked into generated output still trips.
        var effective = IsSelfDeclaredGenerated(lines) ? SecretPatternsOnly(patterns) : patterns;
        if (effective.Count == 0) return findings;

        for (var lineIndex = 0; lineIndex < lines.Length; lineIndex++)
        {
            var line = lines[lineIndex].TrimEnd('\r');
            if (string.IsNullOrWhiteSpace(line))
                continue;

            foreach (var pattern in effective)
            {
                try
                {
                    var match = pattern.Regex.Match(line);
                    if (match.Success)
                    {
                        var matchedText = match.Value.Length > 200
                            ? match.Value[..200] + "..."
                            : match.Value;

                        findings.Add(new PatternFinding(
                            PatternId: pattern.Definition.Id,
                            Category: pattern.Definition.Category,
                            Severity: pattern.Definition.Severity,
                            Confidence: pattern.Definition.Confidence,
                            File: relativePath,
                            Line: lineIndex + 1,
                            Title: pattern.Definition.Title,
                            Description: pattern.Definition.Description,
                            Cwe: pattern.Definition.Cwe,
                            MatchedText: matchedText,
                            Provider: pattern.Definition.Provider,
                            RevokeUrl: pattern.Definition.RevocationUrl));
                    }
                }
                catch (RegexMatchTimeoutException)
                {
                }
            }
        }

        return findings;
    }

    private const string SecretsCategory = "secrets";

    // The <auto-generated> marker is the standard self-declaration Roslyn analyzers honor;
    // generators emit it on the first line or just under a banner comment, so scan the head.
    private static bool IsSelfDeclaredGenerated(string[] lines) =>
        lines.Take(5).Any(l => l.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase));

    private static IReadOnlyList<CompiledPattern> SecretPatternsOnly(IReadOnlyList<CompiledPattern> patterns) =>
        patterns.Where(p => string.Equals(p.Definition.Category, SecretsCategory, StringComparison.OrdinalIgnoreCase))
            .ToList();
}
