using AgentSmith.Contracts.Models;

namespace AgentSmith.Application.Services.Handlers;

/// <summary>
/// Generates a default skill.yaml from detected project characteristics.
/// Pure function — no I/O, no state.
/// </summary>
public static class SkillYamlGenerator
{
    public static string Generate(DetectedProject detected, string sourceType)
    {
        var allItems = detected.Frameworks
            .Concat(detected.Infrastructure)
            .Concat(detected.Sdks)
            .Select(s => s.ToLowerInvariant())
            .ToHashSet();

        var hasBackend = allItems.Any(s =>
            s.Contains("asp.net") || s.Contains("spring") || s.Contains("django") ||
            s.Contains("express") || s.Contains("flask") || s.Contains("rails") ||
            s.Contains("fastapi") || s.Contains("dotnet") || s.Contains(".net"));

        var hasFrontend = allItems.Any(s =>
            s.Contains("react") || s.Contains("angular") || s.Contains("vue") ||
            s.Contains("blazor") || s.Contains("next") || s.Contains("nuxt") ||
            s.Contains("svelte"));

        var hasInfra = allItems.Any(s =>
            s.Contains("docker") || s.Contains("kubernetes") || s.Contains("k8s") ||
            s.Contains("terraform") || s.Contains("helm") || s.Contains("ci") ||
            s.Contains("cd"));

        var hasDatabase = allItems.Any(s =>
            s.Contains("sql") || s.Contains("postgres") || s.Contains("mongo") ||
            s.Contains("redis") || s.Contains("entity framework") || s.Contains("dapper") ||
            s.Contains("prisma") || s.Contains("sequelize"));

        var hasTesting = allItems.Any(s =>
            s.Contains("xunit") || s.Contains("nunit") || s.Contains("mstest") ||
            s.Contains("jest") || s.Contains("mocha") || s.Contains("pytest") ||
            s.Contains("junit"));

        if (!hasBackend && !hasFrontend)
            hasBackend = true;

        return $"""
            # Auto-generated by 'agentsmith init' based on project analysis.
            # Customize as needed.

            input:
              type: ticket
              provider: {sourceType}

            output:
              type: pull-request
              provider: {sourceType}

            context:
              rules: coding-principles.md
              map: code-map.yaml

            roles:
              architect:
                enabled: true
              backend-developer:
                enabled: {(hasBackend ? "true" : "false")}
              frontend-developer:
                enabled: {(hasFrontend ? "true" : "false")}
              devops:
                enabled: {(hasInfra ? "true" : "false")}
              tester:
                enabled: {(hasTesting ? "true" : "false")}
              dba:
                enabled: {(hasDatabase ? "true" : "false")}
              product-owner:
                enabled: false
              security-reviewer:
                enabled: false

            discussion:
              max_rounds: 3
              max_total_commands: 50
              convergence_threshold: 0
            """;
    }
}
