namespace AgentSmith.Contracts.Events;

/// <summary>
/// p0173b: emitted once per ticket seen during a poll cycle, before
/// trigger evaluation. Lets the dashboard count "how many tickets did
/// we look at today" independently from "how many triggered."
/// </summary>
public sealed record TicketScannedEvent(
    string Source,
    string Tracker,
    string TicketId,
    IReadOnlyList<string> Labels,
    DateTimeOffset Timestamp)
    : SystemEvent(Source, SystemEventType.TicketScanned, Timestamp);

/// <summary>
/// p0173b: emitted when a scanned ticket does NOT trigger a pipeline.
/// <see cref="Reason"/> is the categorical why (one of
/// <see cref="TicketSkipReason"/>); <see cref="Detail"/> is the free-form
/// specific answer ("label 'agent-smith' absent", "status 'In Progress'
/// not in trigger_statuses ['To Do','Open']").
/// </summary>
public sealed record TicketSkippedEvent(
    string Source,
    string Tracker,
    string TicketId,
    TicketSkipReason Reason,
    string Detail,
    DateTimeOffset Timestamp)
    : SystemEvent(Source, SystemEventType.TicketSkipped, Timestamp);

/// <summary>
/// p0173b: emitted when a scanned ticket DOES trigger a pipeline. The
/// <see cref="Outcome"/> field carries the claim-service result
/// ("Claimed" / "AlreadyClaimed" / "Rejected" / "Failed"); the
/// dashboard groups by this in the TriggerLog.
///
/// <para><b>RunId is intentionally absent</b> — see PARKED.md item 5.
/// RunId is generated by ExecutePipelineUseCase when the queued
/// ClaimRequest later dequeues; at trigger time only Platform + TicketId
/// + Project + Pipeline are stable. Slice d joins to RunStartedEvent
/// via (Platform, TicketId) — RunStartedEvent's trigger payload is
/// enriched in a follow-up.</para>
/// </summary>
public sealed record TicketTriggeredEvent(
    string Source,
    string Tracker,
    string TicketId,
    string Project,
    string Pipeline,
    string Outcome,
    DateTimeOffset Timestamp)
    : SystemEvent(Source, SystemEventType.TicketTriggered, Timestamp);
