namespace AgentSmith.Domain.Entities;

/// <summary>
/// Execution plan generated by the agent provider.
/// </summary>
public sealed class Plan
{
    public string Summary { get; }
    public IReadOnlyList<PlanStep> Steps { get; }
    public string RawResponse { get; }

    public Plan(string summary, IReadOnlyList<PlanStep> steps, string rawResponse)
    {
        Summary = summary;
        Steps = steps;
        RawResponse = rawResponse;
    }
}
