#!/usr/bin/env node
// Generate CSS custom properties from DESIGN.md frontmatter.
// One source (repo-root DESIGN.md) -> two outputs (website + docs tokens.css).
// Zero deps; hand-rolled YAML parse for the controlled DESIGN.md shape.

import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const designPath = resolve(repoRoot, "DESIGN.md");
const outputs = [
  resolve(repoRoot, "website/src/static/tokens.css"),
  resolve(repoRoot, "docs/stylesheets/tokens.css"),
];
const designCopyForDocs = resolve(repoRoot, "docs/DESIGN.md");

const source = readFileSync(designPath, "utf8");
const frontmatter = extractFrontmatter(source);
const tree = parseYaml(frontmatter);

assertRequired(tree, ["colors.primary", "typography.display-xl.fontSize", "rounded.md", "spacing.xl"]);

const css = emitCss(tree);

for (const out of outputs) {
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, css);
  console.log(`wrote ${out} (${css.length} bytes)`);
}

copyFileSync(designPath, designCopyForDocs);
console.log(`copied DESIGN.md -> ${designCopyForDocs}`);

// ─── helpers ──────────────────────────────────────────────────────────────

function extractFrontmatter(text) {
  const match = text.match(/^---\n([\s\S]*?)\n---/);
  if (!match) throw new Error("DESIGN.md: no YAML frontmatter found between --- markers");
  return match[1];
}

// Minimal YAML parser for the DESIGN.md shape:
//   top-level keys -> 2-space-indented child maps or scalars
//   child maps may have 4-space-indented grandchild scalars
//   scalars: quoted strings, unquoted strings, hex, numbers, dimensions (e.g. 56px, 1.4)
// Comments (#) and blank lines are skipped.
function parseYaml(text) {
  const lines = text.split("\n");
  const root = {};
  const stack = [{ depth: -1, node: root }];

  for (const raw of lines) {
    if (!raw.trim() || raw.trim().startsWith("#")) continue;
    const depth = raw.match(/^( *)/)[1].length;
    const line = raw.trim();

    while (stack.length > 1 && depth <= stack.at(-1).depth) stack.pop();
    const parent = stack.at(-1).node;

    const colon = indexOfTopLevelColon(line);
    if (colon === -1) throw new Error(`unparseable line: "${raw}"`);
    const key = line.slice(0, colon).trim();
    const rest = line.slice(colon + 1).trim();

    if (rest === "") {
      const child = {};
      parent[key] = child;
      stack.push({ depth, node: child });
    } else {
      parent[key] = parseScalar(rest);
    }
  }
  return root;
}

function indexOfTopLevelColon(s) {
  let inQuote = null;
  for (let i = 0; i < s.length; i++) {
    const c = s[i];
    if (inQuote) {
      if (c === inQuote) inQuote = null;
    } else if (c === '"' || c === "'") {
      inQuote = c;
    } else if (c === ":") {
      return i;
    }
  }
  return -1;
}

function parseScalar(v) {
  const t = v.trim();
  if ((t.startsWith('"') && t.endsWith('"')) || (t.startsWith("'") && t.endsWith("'"))) {
    return t.slice(1, -1);
  }
  return t;
}

function assertRequired(tree, paths) {
  for (const p of paths) {
    const parts = p.split(".");
    let node = tree;
    for (const part of parts) {
      if (node == null || typeof node !== "object" || !(part in node)) {
        throw new Error(`required token missing in DESIGN.md frontmatter: ${p}`);
      }
      node = node[part];
    }
  }
}

function emitCss(tree) {
  const lines = [];
  lines.push("/* Auto-generated by tools/build-tokens.mjs from DESIGN.md.");
  lines.push("   Do not hand-edit — change DESIGN.md and rerun the build. */");
  lines.push("");
  lines.push("@font-face {");
  lines.push("  font-family: 'Inter';");
  lines.push("  font-style: normal;");
  lines.push("  font-weight: 100 900;");
  lines.push("  font-display: swap;");
  lines.push("  src: url('https://cdn.jsdelivr.net/npm/@fontsource/inter@5.0.16/files/inter-latin-variable-wghtOnly-normal.woff2') format('woff2-variations');");
  lines.push("}");
  lines.push("");
  lines.push(":root {");

  for (const [key, value] of Object.entries(tree.colors || {})) {
    lines.push(`  --color-${kebab(key)}: ${value};`);
  }
  lines.push("");

  for (const [role, fields] of Object.entries(tree.typography || {})) {
    const base = `--typography-${kebab(role)}`;
    if (fields.fontFamily) lines.push(`  ${base}-family: ${fields.fontFamily};`);
    if (fields.fontSize) lines.push(`  ${base}-size: ${fields.fontSize};`);
    if (fields.fontWeight) lines.push(`  ${base}-weight: ${fields.fontWeight};`);
    if (fields.lineHeight) lines.push(`  ${base}-line-height: ${fields.lineHeight};`);
    if (fields.letterSpacing) lines.push(`  ${base}-tracking: ${fields.letterSpacing};`);
  }
  lines.push("");

  for (const [key, value] of Object.entries(tree.rounded || {})) {
    lines.push(`  --rounded-${kebab(key)}: ${value};`);
  }
  lines.push("");

  for (const [key, value] of Object.entries(tree.spacing || {})) {
    lines.push(`  --spacing-${kebab(key)}: ${value};`);
  }

  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

function kebab(s) {
  return String(s).replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}
